name : telegram-bot
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 */3 * * *' 

jobs:
  run_weather_bot:
    name: Run Weather Bot
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.3

      - name: Setup Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: 16.19.0

      - name: Clean Install NPM Dependencies
        run: npm ci

      - name: Run the Bot
        run: npm start
        env:
          WEATHER_API_TOKEN: ${{ secrets.WEATHER_API_TOKEN}}
          TELEGRAM_BOT_KEY: ${{ secrets.TELEGRAM_TOKEN}}
          
